### PR TITLE
Mark SE-0269 as implemented

### PR DESCRIPTION
**Pull request by Jumhyn**
This was implemented by [PR 23934](https://github.com/apple/swift/pull/23934/) on [apple/swift](https://github.com/apple/swift).

### CODE REVIEW

**Comment by krilnon** [comment]
We should hold on merging this until we know which Swift version SE-0269 is implemented in.

**Comment by Jumhyn** [comment]
Sounds good. I’ll update this PR once that’s settled.

**Comment by tkremenek** [comment]
The release will be 5.3.  A blog post documenting the release process for 5.3 will be published soon.  Feel free to adjust the PR to say 5.3.

**Comment by Jumhyn** [comment]
Thanks @tkremenek! The implemented version has been updated.

**Pull request merged**
