### PR TITLE
[Proposal] Deprecate Tuple Shuffle Expressions

### PR DESCRIPTION
**Pull request by CodaFi**
Coming in late, I know.  Just wanted to get it up and out of the way.

### CODE REVIEW

**Comment by tkremenek** [comment]
The Core Team briefly discussed this proposal and believe it has a lot of traction. An implementation is needed for this proposal to schedule it for active review. Since this is source-breaking, a desired implementation would warn in the existing Swift modes and an error (with fixit) in Swift 5 mode.

Once you have an implementation please assign this PR back to me.

**Comment by Yongjin0919** [comment]
Helpme

**Comment by DougGregor** [comment]
@CodaFi are you interested in pursuing this further or should we close it out?

**Comment by CodaFi** [comment]
It's been a long time since I've last looked at this, but I think I can find some time during spring break to pick it back up considering the other implementations should be merged soon.

**Comment by CodaFi** [comment]
Okay, now I'm going to close this.  Not out of lack of interest, but because I'm driving way too many proposals forward and this one needs a completely different discussion than the one it enjoyed the first time around.

**Pull request closed without merging**
