### PR TITLE
Map Sorting

### PR DESCRIPTION
**Pull request by AnthonyLatsis**
https://github.com/apple/swift/pull/23156

### CODE REVIEW

**Comment by CTMacUser** [comment]
Should the transformation closure be allowed to be throwing too?

**Comment by AnthonyLatsis** [comment]
Thanks, Daryle!

**Comment by AnthonyLatsis** [comment]
@airspeedswift, is the horizon clear to stage this for review?

**Comment by AnthonyLatsis** [comment]
@jckarter, may I propose you the review manager spot? Ben seems to be busy :)

**Comment by calda** [comment]
@tkremenek Do you have a rough timeline for this proposal's official review? I'm talking through some last-minute [changes and improvements](https://forums.swift.org/t/map-sorting/21421/40?u=cal) in the pitch thread, so I want to make sure we have everything finalized before the official review.

Thanks!

**Comment by tkremenek** [comment]
CC @airspeedswift

**Comment by airspeedswift** [comment]
As discussed on the [thread](https://forums.swift.org/t/map-sorting/21421/54) – a proposal to sugar this use case should be folded into a wider discussion of sorting capabilities. Closing pending that.

**Pull request closed without merging**
