### PR TITLE
Proposal to replace 'typealias' with 'associated' for associated type declarations

### PR DESCRIPTION
**Pull request by loiclec**
This has been discussed in the swift-evolution mailing list, and has received positive feedback so far :)

### CODE REVIEW

**Comment by radex** [comment]
+1 for the proposal, keyword name, and proposed approach. I think it would be great if initial support could be landed in Swift 2.2 — doing deprecation and removal in two steps is such a great pattern. It eases the transition, especially as Swift matures, but still leaves us with room to change things without outright breaking of a lot of code.

**Comment by lattner** [comment]
+1, to @DougGregor for consideration.

**Comment by tjw** [comment]
I very much like the idea of splitting up these two concepts, but "associated" seems vague to me, since it doesn't specify the kind of relationship, just that there is one. A few possible spellings might be "type", "typearg", "needs_type", or anything that reads as there being a placeholder in the protocol that would be filled by a type-shaped thing.

**Comment by wiruzx** [comment]
+1 for the `type` keyword. Scala uses `type` for [abstract types](http://docs.scala-lang.org/tutorials/tour/abstract-types.html) too.

**Comment by anandabits** [comment]
This conflicts with the proposal to use a type keyword for type-level members unifying static and class.  If we are going to have a type keyword we'll only be able to use it in one way or the other, not both.  I don't have an opinion, just pointing this out.

**Comment by tjw** [comment]
Unifying those (and getting rid of `static`, which I've never liked) would be good too. Using `type` for that would work, but something like `Self func foo(...)` or `func Self.foo(...)` also seem like they'd work (and make it clear that the type being referred to is the one defining the current scope.

**Comment by DougGregor** [comment]
Please keep the discussion on the swift-evolution mailing list :)

**Pull request merged**
