### PR TITLE
add Commonly Proposed Changes section

### PR DESCRIPTION
**Pull request by masters3d**
https://lists.swift.org/pipermail/swift-evolution/Week-of-Mon-20151214/003799.html

### CODE REVIEW

**Comment by lattner** [comment]
Awesome, please move this to the very bottom of the page though (under "Accepted proposals for Swift 2.2") and I'll merge it.  Thanks again.

**Comment by DougGregor** [comment]
Thanks for working on this! I'd rather this content be in a separate document, because it's going to grow long, and moving the content to the bottom will be less discoverable. Instead, let's have a link to the separate document (e.g., commonly_proposed.md) in the first bulleted list of README.md.

**Comment by lattner** [comment]
Ah, that makes sense to me, thanks Doug.

**Comment by masters3d** [comment]
moved to its own file and added a couple more entries. thanks!

**Comment by lattner** [comment]
Cool, please squash these and I'll merge it.  Thanks again!

**Comment by masters3d** [comment]
Closing this in favor of https://github.com/apple/swift-evolution/pull/72

**Pull request closed without merging**
