### PR TITLE
Mark some proposals as implemented

### PR DESCRIPTION
**Pull request by natecook1000**
These 6 are all implemented—there are a few others with at least partial/mostly-done implementations, but I left those alone for now.

### CODE REVIEW

**Comment by benrimmington** [comment]
These should be **Implemented (Swift 4)** — instead of just **Implemented** — for the [status page](https://apple.github.io/swift-evolution/#?version=4).

**Comment by lattner** [comment]
@DougGregor ?

**Comment by DougGregor** [comment]
Yeah, it should be **Implemented (Swift 4)**. Thanks for doing this, @natecook1000

**Comment by natecook1000** [comment]
Thanks @benrimmington — missed that distinction. (Also, there's only five implemented proposals here, SE-0174 just has its bug attached.)

**Comment by DougGregor** [comment]
Thanks!

**Pull request merged**
