### PR TITLE
Assign SE-0315 to placeholder types proposal

### PR DESCRIPTION
**Pull request by Jumhyn**

### CODE REVIEW

**Comment by Jumhyn** [comment]
cc @jckarter I assigned the next available SE number to this proposal just to get the `nnnn` file out of the tree. If I should use another number, or if the manager/schedule info is settled and can be added now, lmk!

**Comment by benrimmington** [comment]
Suggestions:

* Syntax highlighting is missing from the _§Introduction_ examples.

* The optional-type `?` is missing from the _§Motivation_ examples.

  ```diff
  -let losslessStringConverter: (String) -> Double = Double.init
  +let losslessStringConverter: (String) -> Double? = Double.init
  ```

  ```diff
  -let losslessStringConverter = Double.init as (String) -> Double
  +let losslessStringConverter = Double.init as (String) -> Double?
  ```

* A `try` is missing from the `JSONDecoder` and `KeyedDecodingContainer` examples.

  ```diff
  -let dict = JSONDecoder().decode([String: Int].self, from: data)
  +let dict = try JSONDecoder().decode([String: Int].self, from: data)
  ```

  ```diff
  -self.someProp = container.decode(_.self, forKey: .someProp)
  +self.someProp = try container.decode(_.self, forKey: .someProp)
  ```

* Under the comprehensive _§Function signatures_ example, `frobnicate1` should be `frobnicate` (or vice versa).

  ```diff
  -(`frobnicate1`, of course, compiles without this proposal as well)
  +(`frobnicate`, of course, compiles without this proposal as well)
  ```

  (It might also be clearer to group the valid and invalid `frobnicate…` functions in separate extensions, and/or append error comments to the invalid function signatures.)

* There's a "wen necessary" typo, in the _§Top-level placeholder types_ section.

**Comment by Jumhyn** [comment]
Thanks for your suggestions as always @benrimmington, I'll apply them in a separate PR since Joe has gone ahead and done the bookkeeping for this proposal.

**Comment by benrimmington** [comment]
The link below is incomplete, and I think the `**` will need to move to the end of the line.

Should the review be scheduled to begin in 3 days or 5 weeks hence?

```diff
-* Review Manager: [Joe Groff](
-* Status: **Scheduled for review** (June 21...July 6, 2021)
+* Review Manager: [Joe Groff](https://github.com/jckarter)
+* Status: **Scheduled for review (May 21...June 6, 2021)**
```

**Comment by Jumhyn** [comment]
I discussed the June 21st date with Joe privately, so I'm pretty sure it's accurate. I believe other things are taking priority before WWDC. 😄

**Pull request closed without merging**
