### PR TITLE
Introduce typeprivate access control level

### PR DESCRIPTION
**Pull request by goncaloalvarez**

### CODE REVIEW

**Comment by lattner** [comment]
This appears to be an additive proposal and is out of scope for Swift 4 stage 1 goals.

**Comment by DougGregor** [comment]
Closing out-of-scope proposal. When it's in scope, please re-open the PR. Thanks!

**Comment by masters3d** [comment]
@goncaloalvarez Are you planning to submit this for phase 2? I think the window closes April 1.

**Comment by masters3d** [comment]
@goncaloalvarez Can you bring this up to the Swift Evolution? There is a lot of talk about about fileprivate and access modifiers. Something to talk about in the swift evolution mail is: Are all typeprivate public outside the module?

**Pull request closed without merging**
