### PR TITLE
Add swiftpm service manager extension

### PR DESCRIPTION
**Pull request by amraboelela**

### CODE REVIEW

**Comment by tomerd** [comment]
hi @amraboelela thank you for the idea and PR. Was this discusses as pitch in the forums yet? For reference, we normally try to socialize ideas with the community to help define the proposal details.

**Comment by amraboelela** [comment]
No I didn’t.

How do I do that?

**Comment by tomerd** [comment]
Hi @amraboelela the full process is documents https://github.com/apple/swift-evolution/blob/master/process.md

First, you need to socialize and collect feedback about your idea using a forum thread in https://forums.swift.org/c/evolution/pitches, based on that you formulate the proposal as described in the above link

**Comment by tomerd** [comment]
Hi @amraboelela closing this for now, please re-open if interested following the process described above

**Pull request closed without merging**
