### PR TITLE
First draft of proposal for <https://bugs.swift.org/browse/SR-842>.

### PR DESCRIPTION
**Pull request by tjw**

### CODE REVIEW

**Comment by gribozavr** [comment]
@tjw Thank you!  Could you add syntax highlighting to code blocks?

```
>      ```swift
>      func foo() {}
>      ```
```

**Comment by tjw** [comment]
Well, that doesn't look right... trying again.

**Comment by gribozavr** [comment]
The backticks should start at the leftmost column.

**Comment by lattner** [comment]
@gribozavr Did you mean to merge this?  If so, please rename it, link it into the schedule as an unscheduled proposal.

**Comment by gribozavr** [comment]
1fe69d0273cee961cb61c9fe08a7cc97739ad49c and 3a62416d638ea67a675ec8963e8014757f5fbab8.

**Comment by jrose-apple** [comment]
That's not the right proposal. This one's still got the NNNNs in it.

**Pull request merged**
