### PR TITLE
Add a proposal to eliminate value-to-optional coercion in operator arguments.

### PR DESCRIPTION
**Pull request by rudkx**

### CODE REVIEW

**Comment by lattner** [comment]
@rudkx I sent some specific feedback to swift-evolution.  Please revise the proposal however you'd like and lemme know when it is ready to merge.

**Comment by rudkx** [comment]
@lattner I have most of your feedback incorporated, and am taking a quick look at a few more projects before I push a new version.

**Comment by lattner** [comment]
Please email me when you're ready to kick this off.

**Comment by rudkx** [comment]
@lattner There's been a bit of a snag with adding the overloads for equality and identity since they allow things like this to type check now:
  let i = 1
  if i == nil {}

I'm looking into what the options are for continuing to diagnose this while allowing mixed-type comparisons to proceed.

**Pull request merged**
