### PR TITLE
Add new section for Swift 3.1 proposals

### PR DESCRIPTION
**Pull request by benrimmington**
See also apple/swift#4690

### CODE REVIEW

**Comment by benrimmington** [comment]
@jtbandes Please review.

**Comment by lattner** [comment]
@DougGregor please review as well, thanks

**Comment by benrimmington** [comment]
Preview: <https://benrimmington.github.io/swift-evolution/>

**Comment by jtbandes** [comment]
Since #4690 was merged, this seems correct.

**Pull request merged**
