### PR TITLE
Suggested handling of polymorphic selectors

### PR DESCRIPTION
**Pull request by jhaungs**
This pull request is per email with Doug Gregor.

### CODE REVIEW

**Comment by DougGregor** [comment]
I think the terms "polymorphic" and "monomorphic" are a bit confusing here. Can we avoid those terms, and instead talk about this as an approach for dealing with cases where there is no (single) natural Swift method to refer to in `#selector`? It's relevant to both the "provided-by-several-disjoint-classes" and the "dynamically-generated-and-has-no-Swift-declarations" use cases. (Thanks!)

**Comment by lattner** [comment]
@DougGregor please review the update here, and close or merge.  Thanks!

**Comment by lattner** [comment]
@DougGregor please review the update here, and close or merge, this is an edit to a proposal not a new proposal. Thanks!

**Comment by lattner** [comment]
This PR is stale and conflicts, I'm closing it now.  If there is still something that needs to happen, please create a new PR.  Thanks!

**Pull request closed without merging**
