### PR TITLE
Revise SE-0077 according to the rationale

### PR DESCRIPTION
**Pull request by Anton3**
No ready to merge right now, because naming issues are not resolved.
Plus, opinions on chosen precedence group syntax are still incoming.

### CODE REVIEW

**Comment by lattner** [comment]
@Anton3 I think it is ready to merge now, the bike shedding on the names can be specifically cited as something that needs more discussion, which can be done in the review #2 thread.  Sound ok?

**Comment by Anton3** [comment]
@lattner Ready to merge.

**Comment by lattner** [comment]
Great, I'll schedule it for next week, thanks again!

**Comment by lattner** [comment]
Oh, actually @jckarter took over review managerizing it.  Joe, do you want to schedule it, or should I?

**Comment by jckarter** [comment]
I wanted to wait until @dabrahams and @gribozavr had a chance to review the proposed names.

**Comment by jckarter** [comment]
Thanks for the revision @Anton3!

**Pull request merged**
