### PR TITLE
Optional iteration

### PR DESCRIPTION
**Pull request by AnthonyLatsis**
Proposal updates.
@jckarter

### CODE REVIEW

**Comment by AnthonyLatsis** [comment]
Seems like the conflicts are too complex to resolve. I will update the header so we can simply force the change if needed without further corrections.

**Comment by benrimmington** [comment]
@AnthonyLatsis You appear to be editing the wrong file. It was renamed to `proposals/0231-optional-iteration.md` in commit 09f5539e5f541dd1a87ac5844655568757857626. Your branch is 323 commits behind `apple:master`.

**Comment by jckarter** [comment]
Yeah, if you don't mind, could you apply your changes to the top-of-tree version of the proposal?

**Comment by AnthonyLatsis** [comment]
My bad.

**Pull request closed without merging**
