### PR TITLE
Key path literal syntax

### PR DESCRIPTION
**Pull request by michael-lehew**
Update proposal to reflect new ideas regarding short-hand key-path references.

### CODE REVIEW

**Comment by michael-lehew** [comment]
That's fair -- the short version of \ vs # is that the core team wants to save # for future use. It's heritage with macros in C derived languages is appealing, and even as # has been used thus far in swift there is a slight 'perform verb X' aspect to it (#keyPath -> does something returns a string, #available -> does something returns a bool);   #Person.foo.blah could maybe construed that way... except the 'does something'  is a lot more like 'does nothing'.   \ on the other hand has existing precedent in swift of meaning 'behave differently for a moment' (as in string interpolation).  I can tighten that prose up and update the PR if it makes sense.

**Comment by anandabits** [comment]
That's a fair explanation of the rationale.  It makes perfect sense to me.  If this goes through maybe we can get a companion through as well for unbound methods.  Thanks for your work on this proposal!  I'm really excited to see this happen.  :)

**Comment by michael-lehew** [comment]
Thanks Matt, I think that helps considerably.

**Comment by anandabits** [comment]
You're welcome!  This is shaping up to be a really exciting proposal!  Thank you.

**Pull request merged**
