### PR TITLE
Adding proposal to remove associated type inference

### PR DESCRIPTION
**Pull request by austinzheng**
Note that I just started the pre-proposal discussion thread, so you may or may not wish to merge this immediately.

### CODE REVIEW

**Comment by lattner** [comment]
Thanks, I'll kick this off shortly, unless you'd like to wait.  What do you prefer @austinzheng ?

**Comment by DougGregor** [comment]
i suspect in going to be asking for some revisions. Will review tonight.

**Comment by lattner** [comment]
Ok, lemme know when you're ready.  Probably best to email me directly for prompt response :-)

**Comment by austinzheng** [comment]
I'll be standing by tonight for whatever revisions you want to make. Once
they're in, I'll let Chris know and he can kick it off whenever he wants.

**Comment by austinzheng** [comment]
Oh, it's already in. In that case it's probably best for the two of you to just make whatever revisions need to be made directly. Let me know if I can help in any way.

**Comment by DougGregor** [comment]
You can create pull requests to update proposals that are already in. Will send comments via the mailing list soon.

**Pull request merged**
