### PR TITLE
SE-0347: Add clarifying example and supporting text to Introduction section

### PR DESCRIPTION
**Pull request by xedin**

### CODE REVIEW

**Comment by xedin** [comment]
@xwu Does it look good to you? (Cannot add you as a reviewer to this PR).

**Comment by xwu** [comment]
I like it. On line 32, do you mean that it's possible to infer the default type from the _second_ argument?

**Comment by xedin** [comment]
Ah yes, thank you!

**Comment by xedin** [comment]
Fixed.

**Pull request merged**
