### PR TITLE
SE-0155 Revision 2

### PR DESCRIPTION
**Pull request by dduan**
This is the revised version of SE-0155

### CODE REVIEW

**Comment by DevAndArtist** [comment]
Is that a typo?

> ... therefore the expected syntax **in** invalid.

Should it not be
>... therefore the expected syntax is invalid.

**Comment by dduan** [comment]
@DevAndArtist thanks for the catch!

**Comment by dduan** [comment]
I'm closing this temporarily to incorporate some (emerging) results from SE discussions.

**Comment by dduan** [comment]
This is ready for another round of review. Unless you found anything that still need improvements. @rjmccall @jckarter

**Comment by jckarter** [comment]
LGTM. @rjmccall, want to start another round of review?

**Pull request merged**
