### PR TITLE
Improved proposals template

### PR DESCRIPTION
**Pull request by Qbyte248**
Improved the proposals template linguistically.

### CODE REVIEW

**Comment by gribozavr** [comment]
@Qbyte248 Could you squash the commits?

**Comment by Qbyte248** [comment]
@gribozavr I'm sorry I don't know what you mean by "squash".

**Comment by gribozavr** [comment]
The 12 commits in this PR contain unrelated changes that were reverted later in your PR.

https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

or just create another pull request that has the two changes in the effective diff that github shows.

**Comment by Qbyte248** [comment]
Ok I close the current one and try to make a squashed one.

**Pull request closed without merging**
