### PR TITLE
Proposal: Revising access modifier on extensions

### PR DESCRIPTION
**Pull request by DevAndArtist**
Please consider this language change (it feels like a bug fix), because it includes breaking changes.

### CODE REVIEW

**Comment by DevAndArtist** [comment]
Please do not merge or close this PR yet.

**Comment by DevAndArtist** [comment]
@lattner I feel like I can't add any arguments any more, please consider to merge this PR for Swift 3 review. It aims to remove the ability of setting the default access modifier on extension members, which has some side effects that makes the access control inconsistent from my point of view.

**Comment by DevAndArtist** [comment]
@lattner forgotten, deferred or ignored? 🤔

**Comment by lattner** [comment]
Haven't forgotten.

**Comment by lattner** [comment]
Scheduled for tomorrow.

**Pull request merged**
