### PR TITLE
Change leftover links from 'master' to 'main'.

### PR DESCRIPTION
**Pull request by amartini51**

### CODE REVIEW

**Comment by benrimmington** [comment]
There are also a couple of links in [process.md](https://github.com/apple/swift-evolution/blob/main/process.md), and many links in the [proposals](https://github.com/apple/swift-evolution/tree/main/proposals) directory.

**Comment by najacque** [comment]
ah, you beat me to it!  thanks for updating this

**Comment by benrimmington** [comment]
Here's a solution for the Swift.org blog and forums (and external websites), if the `master` branch can be deleted.

<https://github.blog/changelog/2020-07-17-links-to-deleted-branches-now-redirect-to-the-default-branch/>

**Comment by benrimmington** [comment]
The `master` branch for `apple/swift` has already been deleted.

e.g. <https://github.com/apple/swift/blob/master/CHANGELOG.md>

> Branch not found, redirected to default branch.

**Comment by amartini51** [comment]
I started that PR because it looked like the SE repo needed one or two quick fixes, but it turns out that it will need some meaningful attention.  Most of it could probably be a bulk find-and-replace to turn `/master/` into `/main/` in URLs.  I'm closing this incomplete fix.

**Pull request closed without merging**
