### PR TITLE
Clarify from northern hemisphere bias.

### PR DESCRIPTION
**Pull request by timburgess**

### CODE REVIEW

**Comment by lattner** [comment]
I see what you mean, we should clarify this, but "Q4" is just confusing and unclear..

**Comment by kud1ing** [comment]
Suggestions:
* "end of 2016"
* "September - November 2016"

**Comment by lattner** [comment]
I changed it to "late 2016" in b7dee14, thanks.

**Comment by timburgess** [comment]
:+1:

**Pull request closed without merging**
