### PR TITLE
Process: Improvements to "How to propose a change" section

### PR DESCRIPTION
**Pull request by AnthonyLatsis**
Nothing new, mostly reformatting and reorganizing stuff.

### CODE REVIEW

**Review by simanerush — APPROVED** [review]

**Comment by AnthonyLatsis** [comment]
@hborla ping

**Comment by AnthonyLatsis** [comment]
@rjmccall ping

**Comment by AnthonyLatsis** [comment]
@rjmccall ping

**Comment by AnthonyLatsis** [comment]
Thank you, Holly!

**Pull request merged**
