### PR TITLE
Proposal: Union Type

### PR DESCRIPTION
**Pull request by frogcjn**
```swift
var stringOrURL: String | URL = "https://www.apple.com"
```
Please see https://github.com/frogcjn/swift-evolution/blob/master/proposals/xxxx-union-type.md

### CODE REVIEW

**Comment by cezheng** [comment]
Seriously, are you a Java programmer here making a proposal to swift-evolution?

**Comment by frogcjn** [comment]
@cezhang, Java has no union type like this.

**Comment by cezheng** [comment]
I mean your sample code

```swift
let a = new A()
```

**Comment by cezheng** [comment]
Well I personally don't like this proposal, since it is adding complexity to the language while not really simplifying the use cases you mentions.

**Comment by frogcjn** [comment]
@czheng, I have some other people support this proposal.
I think union type is a rational grammar that every programming language should learn about. This feature should finally replace the generic enum solution for optional feature.

by the way.
```
let a = new A()
```
I wrote this kind of code in my Swift project. I would like to use type inference in Swift.
This is so swift way, Why Java? Since this topic is not about my proposal you can discuss this topic other place.

**Comment by cezheng** [comment]
ok, I'm convinced that you have never really written any swift, and still writing a swift proposal
image

**Comment by cezheng** [comment]
What other languages have is not the reason why swift should have the same syntax. Python also claims that switch is not necessary since if else can just do the same things, then why don't you propose to remove switch from swift?

I think for the same reason they remove c-style for and ++, -- from swift, we shouldn't add this to swift since it is adding unnecessary complexity to the language itself.

**Comment by frogcjn** [comment]
@cezheng welcome to discuss on swift-evolution email list.

**Comment by DevAndArtist** [comment]
@frogcjn 

1. You never read any of the swift-evolution rules or threads? Your proposal had no thread before PR.
2. Swift does not support infix operator on types at declaration. The first step in this direction will be [SE-0095](https://github.com/apple/swift-evolution/blob/master/proposals/0095-any-as-existential.md), but thats it for now. 
3. An `|` operator is not welcome from the core team point of view (at least for now).
4. The proposal to remove `.self` magic from types is deferred.
5. This proposal is way out of scope for Swift 3!

This proposal will probably be closed anytime soon, @lattner, @dabrahams?

**Comment by frogcjn** [comment]
@DevAndArtist I have thread before PR.

**Comment by DevAndArtist** [comment]
@frogcjn Actually no haven't, your PR is from 10:45 (my time) where the thread was opened at 11:06. But the point I had is that the community literally had no time to discuss the proposal. You'd know that this is out of scope for Swift 3 and not yet possible at all.

Here is some bikeshedding:

```swift
enum OneOf<T, U> {
	
	case lhs(T)
	case rhs(U)
	
	init(value: T) {
		
		self = .lhs(value)
	}
	
	init(value: U) {
		
		self = .rhs(value)
	}
}

func |<T, U>(_ lhs: T.Type, _ rhs: U.Type) -> OneOf<T, U>.Type {
	
	return OneOf<T, U>.self
}

let test1 = (String.self | Int.self).init(value: "test")
let test2 = (String.self | Int.self).init(value: 42)
```

**Comment by frogcjn** [comment]
@DevAndArtist

I have thread before PR. You can search. I have discussed this porposal way back to February. I have read swift-evolution rules. You can search my thread.

**Comment by frogcjn** [comment]
@DevAndArtist I have wrote details in proposal about why Enum generic is not enough.

**Comment by frogcjn** [comment]
Please see http://article.gmane.org/gmane.comp.lang.swift.evolution/17193/

**Comment by cezheng** [comment]
I just saw more people opposing it than supporting it. I think this is pretty much over.

**Comment by frogcjn** [comment]
@cezheng, this is just a proposal, take it easy. I believe if this feature implemented in Swift will help developer to write their code and make the logic in compiler and developer's code clear.

**Comment by DevAndArtist** [comment]
I'd rather propose in the future for some kind of a variadic generic (where `...T` does not mean the same as `T...`) and a variadic cased enum.

This would solve your problem with `default` on switches.

Bikeshedding:

```swift
enum OneOf<...T> {
	
	...case $#(T)

	init(value: ...T) {
		
		self = .$(value)
	}
}
```

**Comment by frogcjn** [comment]
@DevAndArtist, I like this feature. I think any generic programming language should have this feature.
But I still think using generic to wrap value to implement the union or option feature is not a good solution,

**Comment by cezheng** [comment]
It's you that should take it easy. I'm just showing my own opinion that this proposal is adding complexity to the language while increasing the potential for people to write bad code.

**Comment by frogcjn** [comment]
@cezheng you can give examples and discussion on email list, why the union type is bad. Thanks.

**Comment by DevAndArtist** [comment]
@frogcjn whats the problem with `Optional`? It's a neat feature we have in swift. :) 

The way you're trying to solve it (with the `|` operator) is to complex, because a true union type would merge the universe of same types like `String | String | Int` into `String | Int`. I believe no one would do that (`String | String`) anyway, that's why something like `enum OneOf<...T>` would solve the problem with less complexity. Thats why I personally think there is no need for a union type. ;)

**Comment by DevAndArtist** [comment]
> @cezheng you can give examples and discussion on email list, why the union type is bad. Thanks.

It's not about the type being bad, its about the usage of a such complex type. As you showed it yourself, you'd use it for a simple task. So I ask you why is it necessary to add complexity to solve simple problems that might find a neat solution in the future with less complexity?

I kinda think that I've seen `...T` somewhere on the Swift repository.

**Comment by frogcjn** [comment]
using generic to solve the either/optional/union problem, is not logical and complex.
I have wrote in my proposal.

There are several other reasons:

If you use generic to solve the either/union problem, developer will wrote Either declaration, and library like RxSwift and Alamofire has announced their own Result either type. And their either type have different design but sample ability. The Result either type should be unified by using union.

union type is flatten. generic wrap solution is not flatten.

For example:


typealias ABC  = A | B | C 

typealias ABCD = ABC | D

we just use an existed type ABC to construct ABCD

But how about generic wrap?

**Comment by frogcjn** [comment]
If you construct ABCD with ABC using generic solution,  you'll get two layer, and when you do  `switch` you should write two layer of switch. And you should unwrap two times of that monster type.

**Comment by DevAndArtist** [comment]
> For example:
>
> typealias ABC  = A | B | C
> 
> typealias ABCD = ABC | D
> 
> we just use an existed type ABC to construct ABCD
> 
> But how about generic wrap?

Bikeshedding:

```swift
// we generate the boundary with `A | B` or directly OneOf<A, B>
enum OneOf<...T> {

	...case $#(T)

	// Bikeshedding variadic enum casses:
	// we might need an index to set the value?
	init(index: Int, value: T) {
		
		self = .$index(value)
	}
}

/// Usage:
/// A | B | C == OneOf<A, B, C>
func |<T, U>(_: T.Type, _: U.Type) -> OneOf<T, U>.Type {
	
	// I believe the usage of `type` like this was prposed by Joe Groff
	// I also use the proposal to remove `.self` magic here
	return OneOf<T, U>
}

// Here is how to merge OneOf into a single dimension
func |<...T, U>(_: OneOf<...T>.Type, _: U.Type) -> OneOf<...T, U>.Type {
	
	// Copy and merge types into the new `OneOf` type
	return OneOf<...T, U>
}

func |<T, ...U>(_: T.Type, _: OneOf<...U>.Type) -> OneOf<T, ...U>.Type {
	
	// Copy and merge types into the new `OneOf` type
	return OneOf<T, ...U>
}

func |<...T, ...U>(_: OneOf<...T>.Type, _: OneOf<...U>.Type) -> OneOf<...T, ...U>.Type {
	
	// Copy and merge types into the new `OneOf` type
	return OneOf<...T, ...U>
}
```

Your example will become:

```swift
typealias ABC = A | B | C // or OneOf<A, B, C>
typealias ABCD = ABC | D // merging lhs OneOf with D to OneOf<A, B, C, D>
```

Mission accomplished.

**Comment by frogcjn** [comment]
Union version more complex or generic version?
I think union version is more normal.

**Comment by frogcjn** [comment]
I can't compile your code. I'm really not sure your code will pass the complex generic check 🙃

**Comment by DevAndArtist** [comment]
I believe the complexity hides in merging the types into a single universe (correct me if I'm wrong), because for true union `String | Int | String` == `String | Int` == `Int | String`.

My code won't compile, I've never said it does. This is a bikeshedding example how your problem might be solved with less complexity by giving up merging the type universe.

True the **real** union type cannot be made of an `enum` not even a variadic enum will to the trick, because there is no way to know how huge the universe of `...T` will become when there is something like `A | A | B`. Logically you'd assume you will need only two cases but how would you know that in a type safe manner at compile time?

I'd rather invest my strength into variadic generics, where we also would allow something like this `<...T, ...U>` or `<...T, U>` and the creation of variadic enums, if we'd get variadic structs like the generic manifesto showed us.

Okay I'm done here discussing my vision. I'm out. ;)

**Comment by DevAndArtist** [comment]
Just one simple thing to add:

* If `...T` equals 10 then `<...T, U>` = 10 + 1 = 11 types
* If `...U` equals 17 then `<T, ...U>` = 1 + 17  = 18 types
* If `...T` equals 20 and `...U`equals 22 then `<...T, ...U>` = 20 + 22 = 42 types

**Comment by frogcjn** [comment]
what if OneOf<A, A>?

duplicate variable compile warning?

**Comment by DougGregor** [comment]
Please use the swift-evolution mailing list for discussions.

**Comment by lattner** [comment]
This is clearly out of scope for Swift 3, and has been discussed many times on the list.  Please wait until Swift 3 is done before tackling new feature areas.

**Pull request closed without merging**
