### PR TITLE
Decoupling Floating Point Strides from Generic Implementations

### PR DESCRIPTION
**Pull request by xwu**
Erica and I are hoping to resurrect this proposal, updating it for changes made in the interim.

### CODE REVIEW

**Comment by dabrahams** [comment]
Why does this apply only to `BinaryFloatingPoint` and not `FloatingPoint` in general?

**Comment by xwu** [comment]
Two reasons:

(1) Decimal types (such that may exist in the future) do not accumulate error using the "old" stride algorithm

(2) The maximum exactly representable contiguous integer value, or whatever you want to call it, can only be calculated using significandBitCount, which is a requirement of conformance to BinaryFloatingPoint and not FloatingPoint

**Comment by xwu** [comment]
You are correct, though, that a hypothetical floating point type with radix 3 would not be adequately accommodated. However, the division of labor between FloatingPoint and BinaryFloatingPoint may itself need some re-examination if TernaryFloatingPoint ever becomes a thing.

**Comment by xwu** [comment]
Some further thoughts on this: error arises because we try to represent the results of base 10 arithmetic in base 2. It is possible that someone may wish to create a ternary floating point type, but one sensible use for such a type would be representing the result of operations performed in base 3, not base 10. A TernaryFloatingPoint type that performs ternary arithmetic would not accumulate error on repeated multiplication.

**Comment by dabrahams** [comment]
Decimal representation guarantees that the literal you write in decimal notation can be exactly represented, but it doesn’t prevent error from accumulating when the precision of the representation would need to be exceeded.  This accumulation of error is inherent to floating point with any fixed precision.

**Comment by xwu** [comment]
Of course, d'oh. I'll reflect on how to compute the max exactly representable consecutive integer using the facilities found in FloatingPointType. It might not be pretty.

**Comment by xwu** [comment]
I've replaced `BinaryFloatingPoint` with `FloatingPoint`. Calculations about how many steps are supported now rely on `((end - start) / stride).ulp <= 1`. In the context of a `StrideTo<Double>`, sometimes that means the number of iterations tops out at 2 ** 53 - 2 instead of 2 ** 53. That isn't so elegant but it practice it should do.

**Comment by lattner** [comment]
@stephentyrone Can you give this a sanity check?  I'd like to make sure it looks basically ok to you before merging it, thanks!

**Comment by stephentyrone** [comment]
@lattner I think this is good enough to proceed.  There's may be some discussion to be had about what the type of `_step` should be, but I think that swift-evolution is a good place for that.

**Comment by lattner** [comment]
thanks!

**Comment by erica** [comment]
Thank you all!

**Pull request merged**
