### PR TITLE
update to current

### PR DESCRIPTION
**Pull request by CharlesJS**

### CODE REVIEW

**Comment by CharlesJS** [comment]
Sorry; was trying to figure out how to updating my private fork to the latest, not the other way around.

**Comment by jtbandes** [comment]
`git fetch origin && git push -f fork origin/master:master` :smile:

**Comment by CharlesJS** [comment]
Yeah, I was feeling lazy, so I Googled how to do it in Github's interface. I'll just use the command line next time. Pretty embarrassing.

Is there any way to delete these pull requests?

**Comment by jtbandes** [comment]
Not that I'm aware of.

**Comment by CharlesJS** [comment]
So if someone decided to submit a large number of pull requests made up of text touting the virtues of discount pharmaceuticals for the treatment of erectile dysfunction, there would be nothing to be done about it?

I think I see a flaw in this system.

**Comment by jtbandes** [comment]
Yeah...
http://stackoverflow.com/a/18318431

**Pull request closed without merging**
