### PR TITLE
Adding

### PR DESCRIPTION
**Pull request by UnknownTjz**
Adding

### CODE REVIEW

**Comment by rjmccall** [comment]
I'm not sure what's going on with this PR, but if you'd like to re-open it, please break it into separate PRs for each logically-related change, add a real description of the change, and make sure the PR is mergeable; otherwise I'm afraid this looks like PR spam.

**Comment by Jumhyn** [comment]
I think the goal here was to merge all changes that have been inadvertently merged into `máster` into `main`.

**Comment by benrimmington** [comment]
When the [last pull request](https://github.com/apple/swift-evolution/pulls?q=is%3Apr+is%3Aopen+base%3Amaster) for `master` is closed, that branch could be deleted.

**Comment by xwu** [comment]
I just went ahead and changed the base for that PR

**Comment by xwu** [comment]
#1784

**Pull request closed without merging**
