### PR TITLE
[gardening] Update SE-0195 and SE-0196 for implementation status

### PR DESCRIPTION
**Pull request by xwu**

### CODE REVIEW

**Comment by krilnon** [comment]
Can you update the copyright for index.css and index.js as well? I think those are all the places it shows up in this repo and it'd be great to update them at once.

**Comment by xwu** [comment]
@krilnon Done and ready for merge.

**Comment by lattner** [comment]
Thanks!

**Comment by lattner** [comment]
Actually, this should be 4.2 according to https://swift.org/blog/4-2-release-process/  sorry for the confusion.

**Comment by xwu** [comment]
Ha, yup, surprise. I've raised #795.

**Pull request merged**
