### PR TITLE
Create 0052-enforcing_calling_super.md

### PR DESCRIPTION
**Pull request by drumnkyle**

### CODE REVIEW

**Comment by DougGregor** [comment]
I'm closing out PRs for proposals that are out of scope for [Swift 4 stage 1](https://github.com/apple/swift-evolution/blob/master/README.md#development-major-version--swift-40). When we open up the process to the point where this proposal can be in scope, please re-open the pull request.

**Comment by drumnkyle** [comment]
@DougGregor you said to reopen this, but I don’t seem to have access to. I run into plenty of times where there are bugs in iOS Development, because people forget to call super. It would be a really nice safety feature to have this.

**Comment by DougGregor** [comment]
In general, it's okay to open a new pull request if needed. However, discussion should happen on the swift-evolution mailing list first and achieve critical mass before opening a new pull request.

**Comment by drumnkyle** [comment]
@DougGregor Are you saying I have to restart the whole process? I went through the evolution process a long time ago and then submitted this after that. Then, it was never reviewed and just delayed.

**Pull request closed without merging**
