### PR TITLE
Tail Call Optimization attribute and modifier

### PR DESCRIPTION
**Pull request by griotspeak**
Add a `@tailrec` attribute and `tail` modifier allowing the compiler to emit errors when tail call optimization  will not be used.

### CODE REVIEW

**Comment by kostiakoval** [comment]
Is there are See swift-evolution thread for where this features was discussed? Can you include it ? 

"Swift-evolution thread: link to the discussion thread for that proposal" in [template.md](https://github.com/apple/swift-evolution/blob/master/0000-template.md)

**Comment by griotspeak** [comment]
Thanks for pointing that out.

**Comment by iUtvikler** [comment]
Could you add newlines above and below the *Alternatives considered* section?

Also i'm not sure I understand the **Proposed Solution**.

It was my understanding that the *tail* modifier would be a modifier on the return statement where you do the tail call.

```swift
func sumRecursively(numbers: [Int], _ total: Int = 0) -> Int {
    guard let head = numbers.first else {
        return total
    }
    
    let tail = Array(numbers.dropFirst())
    
    tail return sumRecursively(tail, head + total)
}
```
[Example from natashatherobot.com](https://www.natashatherobot.com/functional-swift-tail-recursion/)

And i thought the *@tailrec* function attribute was only needed on a public API that wants to be externally tail-callable.

Can`t think of an example of that..

**Comment by lattner** [comment]
@griotspeak It was great to meet you TJ!  I'm sorry that this is not in scope for Swift 3, but there will certainly be another release...

**Comment by DougGregor** [comment]
I'm closing out PRs for proposals that are out of scope for [Swift 4 stage 1](https://github.com/apple/swift-evolution/blob/master/README.md#development-major-version--swift-40). When we open up the process to the point where this proposal can be in scope, please re-open the pull request.

**Pull request closed without merging**
