### PR TITLE
Extend Optional Chaining to Function, Initializer, and Subscript Parameters

### PR DESCRIPTION
**Pull request by liam923**
This is a proposal to extend optional chaining to parameters.

### CODE REVIEW

**Comment by marcusrossel** [comment]
I really like the idea, as it basically shifts the responsibility of handling `nil`-values from the function author to the function user. This might reduce the number of functions that take optional parameters, as it isn't more convenient than using the suggested syntax, which should in turn result in more functions with non-optional return values. It reminds me of the `rethrows` keyword, which basically makes a function throwing is you pass a throwing closure. And your syntax makes the return type of a function optional if you pass it an optional. This seems very consistent with Swift as a whole.

**Comment by liam923** [comment]
@marcusrossel I hadn't thought about its similarity to `rethrows`, but now that you mention it, I agree that it's similar. I'm glad that you agree with me that it conforms with Swift's design. I think that the syntax is consistent with optional chaining and optionals as a hole.

**Comment by lattner** [comment]
This is an additive proposal that is out of scope for Swift 3.  It also has not had substantial public discussion on the mailing list.  Please wait until after Swift 3 is done to bring this back up.

**Comment by liam923** [comment]
@lattner When will that be? After Swift 3's formal release?

**Comment by lattner** [comment]
Sometime in august.

**Pull request closed without merging**
