### PR TITLE
Adding Adrian as author to 0095

### PR DESCRIPTION
**Pull request by austinzheng**
(see title)

### CODE REVIEW

**Comment by lattner** [comment]
@DevAndArtist look ok to you?

**Comment by anandabits** [comment]
This still needs to be updated to reflect the decision to use lowercase `any` rather than uppercase `Any`.

**Comment by austinzheng** [comment]
@anandabits I'll open another PR after this one goes in.

**Comment by DevAndArtist** [comment]
@lattner @austinzheng feel free. ;)

**Comment by DevAndArtist** [comment]
@lattner I'm probably not available on May 28 and hardly available on May 29. (Time difference: 19:00 at my time equals 9-10:00 when Apple keynote starts.) But I don't think this should be problem.

**Comment by austinzheng** [comment]
@lattner, whenever you have a moment this PR is good to go.

**Pull request merged**
