### PR TITLE
[SE-0187] Change status to "Implemented (Swift 5)"

### PR DESCRIPTION
**Pull request by benrimmington**

### CODE REVIEW

**Comment by benrimmington** [comment]
@moiseev @rjmccall Can this proposal be marked as **Implemented (Swift 5)**?

**Comment by moiseev** [comment]
Yes. Thank you.

**Comment by moiseev** [comment]
Depending on how https://github.com/apple/swift/pull/13807 goes, this should be probably changed to reflect that this feature is available earlier, in Swift 4.1.

**Comment by rjmccall** [comment]
Agreed.

**Pull request merged**
