### PR TITLE
Proposal: Factory Initializers

### PR DESCRIPTION
**Pull request by rileytestut**
Swift-Evolution Thread: https://lists.swift.org/pipermail/swift-evolution/Week-of-Mon-20151214/003192.html

### CODE REVIEW

**Comment by DougGregor** [comment]
I'm closing out PRs for proposals that are out of scope for [Swift 4 stage 1](https://github.com/apple/swift-evolution/blob/master/README.md#development-major-version--swift-40). When we open up the process to the point where this proposal can be in scope, please re-open the pull request.

**Comment by kcfancher** [comment]
Now that Stage 2 is open I'd be in favor of re-opening this proposal.

**Comment by rileytestut** [comment]
@kcfancher yup! Opened it up again in Swift Evolution, and Feedback is still positive so I'm happy to re-open now.

**Comment by rileytestut** [comment]
@DougGregor doesn't appear that I have the ability to reopen this PR myself (no "comment and reopen" button). Would you mind re-opening it?

**Pull request closed without merging**
