### PR TITLE
Proposal to synthesize Equatable/Hashable for value types.

### PR DESCRIPTION
**Pull request by allevato**

### CODE REVIEW

**Comment by allevato** [comment]
I've just pushed a small update to this proposal to clarify some things that have been discovered during the process of writing the WIP implementation above.

**Comment by benrimmington** [comment]
@allevato Please see PR allevato/swift-evolution#1

**Comment by benrimmington** [comment]
@allevato Based on apple/swift#9758 you might need to:

* restore the _original type declaration_ sentence;
* remove the **Location of synthesized conformances** section.

**Comment by allevato** [comment]
Thanks for the heads up, @benrimmington. I updated the proposal and it looks like apple/swift#9758 just got merged so I'll bring my prototype in sync with that as well.

**Comment by trevor-e** [comment]
It would be really awesome if a synthesis framework were exposed to developers so that libraries could leverage a form of code generation, similar to Java's annotation processing.

**Comment by lattner** [comment]
Hi @allevato , I'd like to kick this off for formal review soon.  Please check the proposal for any last minute revisions that you'd like.  Is there an implementation available for this?

**Comment by CodaFi** [comment]
The implementation is available at https://github.com/apple/swift/pull/9619

**Comment by lattner** [comment]
One other point, please make sure the test case includes a test for indirect enums.

**Comment by lattner** [comment]
Thanks for the link @CodaFi .  @allevato let me know when you're ready and I'll kick off review.

**Pull request merged**
