### PR TITLE
proposal for unaligned loads and stores

### PR DESCRIPTION
**Pull request by glessard**
Implementation PR: https://github.com/apple/swift/pull/41033

### CODE REVIEW

**Comment by rjmccall** [comment]
@glessard Is this still awaiting an implementation?

**Comment by glessard** [comment]
The proposal and implementation are ready for review.

**Comment by glessard** [comment]
I could remove excessive references to drafts, I guess.

**Comment by rjmccall** [comment]
Ah, I see the link in the PR summary.  Could you link it from the document, please?  And yeah, if there's any draft cleanup you want to do, please do so.

**Comment by glessard** [comment]
@rjmccall Ready to go on my end; let me know if you need any other changes.

**Comment by rjmccall** [comment]
Thanks.  We'll try to talk about it in the Core Team ASAP and figure out how it's going to be scheduled, but I wanted to make sure you felt it was ready before we started that process.

**Comment by rjmccall** [comment]
We'd like to go ahead and run this.  I'll be review manager.  I think two weeks, running from March 30th until April 12th, is probably appropriate; is that okay with you as the author?

**Comment by glessard** [comment]
Sounds great. Thanks!

**Comment by rjmccall** [comment]
> `loadUnaligned` has a `debugPrecondition` for POD-ness. I'll clarify this in the document and in the doc-comment.

Thank you.

**Comment by glessard** [comment]
Regarding `storeBytes` and `storeBytesUnaligned`: one issue here is that the destination is always, by definition, byte-aligned. At the builtins level, there is also not a different way to spell the two. If we had both functions, they would be identical in release mode, and would otherwise only differ by their set of `debugPrecondition` calls.

**Comment by rjmccall** [comment]
> Regarding `storeBytes` and `storeBytesUnaligned`: one issue here is that the destination is always, by definition, byte-aligned. At the builtins level, there is also not a different way to spell the two. If we had both functions, they would be identical in release mode, and differ only by their set of `debugPrecondition` calls.

I mean, we could add a builtin that does an aligned store.  But in fact we don't need to: since you're requiring the type to be POD, you can simply use the existing initialize or assign builtin.

**Comment by rjmccall** [comment]
Do you want me to put this into review?  I can just make these same comments in the review thread, and we can see what the community thinks.  Worst case, the Core Team asks you to revise the proposal.

**Comment by glessard** [comment]
Yes, go ahead. Thanks!

**Pull request merged**
