### PR TITLE
Mark SE-0145 and SE-0082 as implemented

### PR DESCRIPTION
**Pull request by BasThomas**

### CODE REVIEW

**Comment by jtbandes** [comment]
Thanks @BasThomas. Please keep them in numerical order. While you're at it, could you update 0082?

@ddunbar is it correct that these are implemented for 3.1 and not 4?

**Comment by aciidb0mb3r** [comment]
Yes these are implemented for 3.1

**Comment by BasThomas** [comment]
Oops, fixed!

**Comment by BasThomas** [comment]
Updated 0082 as well.

**Pull request merged**
