### PR TITLE
Update SE-0110's status

### PR DESCRIPTION
**Pull request by BasThomas**
It was accepted in https://lists.swift.org/pipermail/swift-evolution-announce/2016-July/000215.html

### CODE REVIEW

**Comment by benrimmington** [comment]
@BasThomas, see the [comments in PR 726](https://github.com/apple/swift-evolution/pull/726#discussion_r123172100).

Part of SE-0110 was reverted/deferred, due to a [usability regression](https://lists.swift.org/pipermail/swift-evolution-announce/2017-June/000386.html).

Which of the [proposal states](https://github.com/apple/swift-evolution/blob/master/process.md#proposal-states) would be the most accurate?

**Comment by BasThomas** [comment]
I think "accepted with revisions" might make sense. Otherwise a "partially implemented" status (like you suggested) might be a good alternative. What do you think?

**Comment by masters3d** [comment]
I think deferred is the best status given the supplied link. https://lists.swift.org/pipermail/swift-evolution-announce/2017-June/000386.html

**Comment by BasThomas** [comment]
Ping @DougGregor — what would be the appropriate status?

**Comment by DougGregor** [comment]
This proposal is mostly-but-not-completely implemented. I prefer to leave it in the “accepted” state until we are sure it is done, which we hope will be within the next few months

**Pull request closed without merging**
