### PR TITLE
Set implementation version of SE-0143 to Swift 4.1

### PR DESCRIPTION
**Pull request by broomburgo**
I simply set the status of SE-0143 to **Implemented (Swift 4.1)**

### CODE REVIEW

**Comment by linqingmo** [comment]
No, Swift4.1 Swift runtime does not yet support dynamically querying conditional conformance. So Swift4.2 is correct.

**Comment by linqingmo** [comment]
```swift
protocol P {
    func test()
}

extension Array: P where Element: P {
    func test() {
        forEach { $0.test() }
    }
}

class T: P {
    func test() {
        print("Support dynamically querying conditional conformance.")
    }
}

let array = [T(), T()]
array.test() // Swift 4.1 works

func testDynamically(_ a: Any) {
    if let a = a as? P {
        a.test() // Swift 4.2
    } else {
        print("Dose not support dynamically querying conditional conformance.") // Swift4.1
    }
}

testDynamically(array)
```

**Comment by broomburgo** [comment]
Thanks a lot for the clarification, this is huge, I shouldn't have missed it.

**Comment by linqingmo** [comment]
You’re welcome.

**Pull request closed without merging**
